### ISSUE TITLE
Some feedback and suggestions

### ISSUE THREAD

**Issue by puwau** [Toliann/Tolian-Moons#2]
Hello, I saw it lot of what you have made moons,I think They are all pretty good, But many of them are not suitable as outdoor maps...
Because the overall map is too large and also too far from the facilities,it will result in spending too much time on the transportation process of goods.
Suggest shrinking the map slightly and setting the facility entrance closer, And set up multiple side doors in different positions to better integrate with the large map.
For example 'Echelon' may not have many decorations, but the atmosphere and distance are just right(One shortcoming is that Echelon there is not much difference between the side door and the main entrance, It is recommended that you try to distinguish them.)
Aonally, 'Azure' some issues,which may squeeze out the spaceship during landing,prevent outdoor monsters from moving,And lighting seems to affect indoor environments.
(Also, I'm sorry that I don't know English.The above is all the content I described through machine translation. I hope it did not offend you)
(I think you should be more suitable for making games Instead of Lethal Company's mod...)

**Comment by Toliann** [comment]
1. I understand you're talking about the Celestria moon? It will get its redesign a little when the LLL update comes out and the chips that come with it
2. I will fix the problems on Azure soon

**Comment by Toliann** [comment]
There will be a patch for the large moons when the LLL update comes out which will allow random landing points which will give new gameplay for these moons


1. Nyx has plans to add a fire entrance. Nimbus has a fire entrance
2. yes
3. Maybe I'll change that in a future update
4. Yeah, I was notified about it on the modding server in my thread


> for better translation you can use DeepL or ChatGPT_

https://discord.gg/ufR2gNDp Lethal Company Modding server
https://discord.com/channels/1168655651455639582/1208849588539101294 my thread on this server


I liked your review and will take it into account in the next updates

**Comment by puwau** [comment]
I'm glad I could help, I like your work too. Looking forward to your updates!
The random landing points design feels like it be interesting. Clever idea :)
I can't accept the server invite for now Problems with little time due to language barrier and recent work, I'm sorry about that...
