### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by Kuroo2021** [Toliann/Tolian-Moons#4]
When choosing a moon from the pack, it gets stuck on generating a seed. This are the mods 0190f6f1-1c9a-b324-69ee-adea3c190748

**Comment by Toliann** [comment]
can i get a log?  C:\Users\????\AppData\LocalLow\ZeekerssRBLX\Lethal Company\Player.log

**Comment by Kuroo2021** [comment]
> can i get a log? C:\Users????\AppData\LocalLow\ZeekerssRBLX\Lethal Company\Player.log

Way to long ago. :(
